import { Sale, db } from '../db.ts';

export const formatNaira = (amount: number) => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0
  }).format(amount);
};

export const shareReceiptToWhatsApp = (sale: Sale) => {
  const shopName = localStorage.getItem('shop_name') || 'NaijaShop';
  const shopInfo = localStorage.getItem('shop_info') || '';
  const date = new Date(sale.timestamp).toLocaleString('en-NG', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
  
  const transId = sale.id ? String(sale.id).padStart(5, '0') : 'N/A';

  let message = `🛍️ *${shopName.toUpperCase()}*\n`;
  if (shopInfo) message += `📍 ${shopInfo}\n`;
  message += `--------------------------\n`;
  message += `📜 *RECEIPT #${transId}*\n`;
  message += `📅 Date: ${date}\n`;
  message += `--------------------------\n`;
  message += `📦 *ITEMS:*\n`;
  
  sale.items.forEach(item => {
    const itemTotal = item.price * item.quantity;
    message += `• ${item.name} x ${item.quantity} ... ${formatNaira(itemTotal)}\n`;
  });
  
  message += `--------------------------\n`;
  message += `💰 *TOTAL: ${formatNaira(sale.total)}*\n`;
  message += `--------------------------\n`;
  message += `🙏 *Thank you for your business!*\n`;
  message += `\n_Generated by NaijaShop POS_ 🇳🇬`;

  const encodedMessage = encodeURIComponent(message);
  window.open(`https://api.whatsapp.com/send?text=${encodedMessage}`, '_blank');
};

export const generateShopKey = async () => {
  const inventory = await db.inventory.toArray();
  const users = await db.users.toArray();
  const shopName = localStorage.getItem('shop_name') || 'NaijaShop';
  const shopInfo = localStorage.getItem('shop_info') || '';

  const payload = {
    inventory,
    users,
    settings: {
      shopName,
      shopInfo
    }
  };

  const jsonStr = JSON.stringify(payload);
  const base64 = btoa(encodeURIComponent(jsonStr).replace(/%([0-9A-F]{2})/g, (match, p1) => 
    String.fromCharCode(parseInt(p1, 16))
  ));
  
  const key = `SHOP-KEY-${base64}`;
  const message = `🚀 *Shop Setup Key for ${shopName}*\n\nCopy the text below and paste it into your Shop Manager app to sync inventory and staff.\n\n${key}`;

  try {
    await navigator.clipboard.writeText(key);
    alert('Setup Key copied to clipboard! You can now paste it into WhatsApp.');
  } catch (err) {
    console.error('Clipboard failed', err);
  }

  if (navigator.share && key.length < 1500) {
    try {
      await navigator.share({
        title: 'Staff Setup Key',
        text: message
      });
    } catch (e) {
      window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`, '_blank');
    }
  } else {
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message.substring(0, 1500))}`, '_blank');
  }
};

export const decodeShopKey = (key: string) => {
  const trimmedKey = key.trim();
  if (!trimmedKey.includes('SHOP-KEY-')) return null;
  
  try {
    const match = trimmedKey.match(/SHOP-KEY-([A-Za-z0-9+/=]+)/);
    if (!match) return null;
    
    const base64 = match[1];
    const jsonStr = decodeURIComponent(Array.prototype.map.call(atob(base64), (c: any) => 
      '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
    ).join(''));
    
    return JSON.parse(jsonStr);
  } catch (e) {
    console.error('Decode error:', e);
    return null;
  }
};

/**
 * Robust Backup Utility with Triple-Fallback Logic
 * Logic:
 * 1. Immediate Strategy: Minimizes async work before navigator.share
 * 2. Stage 1: Attempt to share as a File (.json)
 * 3. Stage 2: Attempt to share as Text String (Prefix: "NaijaShop Backup Data: ")
 * 4. Stage 3: Direct Browser Download (Final Safety Net)
 */
export const backupToWhatsApp = async (data: any) => {
  const shopName = data.shopName || 'NaijaShop';
  const timestamp = data.timestamp || Date.now();
  const dateStr = new Date(timestamp).toISOString().split('T')[0];
  const fileName = `${shopName.replace(/\s+/g, '_')}_Backup_${dateStr}.json`;
  
  // Prepare all data synchronously to maintain "User Gesture" as much as possible
  const jsonString = JSON.stringify(data, null, 2);
  const minifiedJson = JSON.stringify(data);
  const shareTitle = `Shop Backup: ${shopName}`;
  const shareText = `This is my Secure Shop Backup for ${dateStr}. Keep this file safe. To restore, just share this file back to the POS App.`;

  // Start Triple-Fallback Logic
  if (navigator.share) {
    try {
      // --- STAGE 1: SHARE FILE ---
      const blob = new Blob([jsonString], { type: 'application/json' });
      const file = new File([blob], fileName, { type: 'application/json' });

      // We use try/catch directly instead of navigator.canShare for maximum "immediacy"
      await navigator.share({
        title: shareTitle,
        text: shareText,
        files: [file]
      });
      
      await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
      return; // Success!
    } catch (stage1Error) {
      console.warn("Stage 1 (File Share) failed. Falling back to Stage 2 (Text Share)...", stage1Error);

      try {
        // --- STAGE 2: SHARE TEXT ---
        // Some browsers (like Samsung Internet or older Safari) block file sharing but allow text.
        // Format as requested: "NaijaShop Backup Data: [JSON String]"
        await navigator.share({
          title: shareTitle,
          text: `NaijaShop Backup Data: ${minifiedJson}`
        });
        
        await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
        return; // Success!
      } catch (stage2Error) {
        console.error("Stage 2 (Text Share) also failed.", stage2Error);
      }
    }
  }

  // --- STAGE 3: DIRECT DOWNLOAD (FINAL FALLBACK) ---
  // If navigator.share failed or doesn't exist, provide a local download link.
  try {
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
    alert("Safe sharing was restricted by your phone's browser settings. Your backup has been saved to your 'Downloads' folder instead. Please find the file and send it to your WhatsApp for safekeeping.");
  } catch (stage3Error) {
    console.error("Critical failure: Stage 3 download failed.", stage3Error);
    alert("Backup failed completely. Please try again or contact support.");
  }
};
