
import { Sale, db, User, Customer, Category, InventoryItem, clearAllData } from '../db.ts';
import pako from 'pako';

const MASTER_SALT = "NaijaPOS_2025_Sec" + "ret_Keep_Safe_99";

export const formatNaira = (amount: number) => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0
  }).format(amount);
};

export const shareReceiptToWhatsApp = async (sale: Sale) => {
  const snSetting = await db.settings.get('shop_name');
  const saSetting = await db.settings.get('shop_address');
  
  const shopName = snSetting?.value || localStorage.getItem('shop_name') || 'NaijaShop';
  const shopInfo = saSetting?.value || localStorage.getItem('shop_info') || '';
  
  const date = new Date(sale.timestamp).toLocaleString('en-NG', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
  
  const transId = sale.id ? String(sale.id).padStart(5, '0') : 'N/A';

  let message = `🛍️ *${shopName.toUpperCase()}*\n`;
  if (shopInfo) message += `📍 ${shopInfo}\n`;
  message += `--------------------------\n`;
  message += `📜 *RECEIPT #${transId}*\n`;
  message += `📅 Date: ${date}\n`;
  message += `--------------------------\n`;
  message += `📦 *ITEMS:*\n`;
  
  sale.items.forEach(item => {
    const itemTotal = item.price * item.quantity;
    message += `• ${item.name} x ${item.quantity} ... ${formatNaira(itemTotal)}\n`;
  });
  
  message += `--------------------------\n`;
  message += `💰 *Total Bill: ${formatNaira(sale.total)}*\n`;

  if (sale.walletUsed && sale.walletUsed > 0) {
    message += `💳 Paid from Wallet: -${formatNaira(sale.walletUsed)}\n`;
  }

  if (sale.cashPaid && sale.cashPaid > 0) {
    message += `💵 Cash Paid: ${formatNaira(sale.cashPaid)}\n`;
  }
  
  if (sale.paymentMethod === 'Debt' || sale.paymentMethod === 'Partial') {
    const remainingDebt = Math.max(0, sale.total - (sale.walletUsed || 0) - (sale.cashPaid || 0));
    message += `--------------------------\n`;
    message += `⚠️ *BALANCE OWED (DEBT): ${formatNaira(remainingDebt)}*\n`;
    message += `📌 Status: Partially Settled\n`;
  } else {
    const totalPayment = (sale.walletUsed || 0) + (sale.cashPaid || 0);
    message += `✅ Total Paid: ${formatNaira(totalPayment)}\n`;
  }
  
  message += `--------------------------\n`;

  if (sale.customer_phone) {
    const customer = await db.customers.where('phone').equals(sale.customer_phone).first();
    if (sale.walletSaved && sale.walletSaved > 0) {
      message += `✨ Change Saved to Wallet: +${formatNaira(sale.walletSaved)}\n`;
    }
    if (customer) {
      message += `🏦 Your Wallet Balance: ${formatNaira(customer.walletBalance)}\n`;
    }
    message += `--------------------------\n`;
  }

  message += `🙏 *Thank you for your business!*\n`;
  message += `\n_Generated by NaijaShop POS_ 🇳🇬`;

  const encodedMessage = encodeURIComponent(message);
  window.open(`https://api.whatsapp.com/send?text=${encodedMessage}`, '_blank');
};

export const backupToWhatsApp = async (data: any, excludePhotos = false): Promise<BackupResult> => {
  const finalData = excludePhotos ? {
    ...data,
    inventory: data.inventory.map(({image, ...rest}: any) => rest),
    categories: data.categories.map(({image, ...rest}: any) => rest)
  } : data;

  // Mark as Master Backup for restore identification
  finalData.type = 'MASTER_BACKUP';

  const jsonString = JSON.stringify(finalData);
  const sizeMB = jsonString.length / (1024 * 1024);
  const isLarge = sizeMB > 20;

  if (isLarge && !excludePhotos) {
    if (confirm(`⚠️ LARGE BACKUP: Your data is ${Math.round(sizeMB)}MB because of photos. This might fail on slow WhatsApp networks. Backup text-only instead?`)) {
      return backupToWhatsApp(data, true);
    }
  }

  const shopName = data.shopName || 'NaijaShop';
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toISOString().split('T')[0];
  const fileName = `NAIJASHOP_MASTER_${excludePhotos ? 'LITE_' : ''}${dateStr}.json.gz`;

  const uint8Data = new TextEncoder().encode(jsonString);
  const compressed = pako.gzip(uint8Data);
  
  if (navigator.share) {
    try {
      const blob = new Blob([compressed], { type: 'application/gzip' });
      const file = new File([blob], fileName, { type: 'application/gzip' });
      await navigator.share({ 
        title: `Master Backup: ${shopName}`, 
        text: `Secure encrypted shop backup. Keep this file safe. Date: ${dateStr}`, 
        files: [file] 
      });
      await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
      return { success: true, method: 'FILE_SHARE', fileName };
    } catch (e) {
      console.warn("Share failed, falling back to download...");
    }
  }

  try {
    const blob = new Blob([compressed], { type: 'application/gzip' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
    await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
    return { success: true, method: 'DOWNLOAD', fileName };
  } catch (e) {
    return { success: false, method: 'DOWNLOAD' };
  }
};

/**
 * FULL SYSTEM RESTORE
 * Wipes the database and injects 100% of the backed-up data.
 */
export const restoreFullBackup = async (data: any) => {
  if (data.type !== 'MASTER_BACKUP') {
    throw new Error("Invalid file. This is not a NaijaShop Master Backup.");
  }

  // 1. Wipe everything first to avoid ID collisions
  await clearAllData();

  // 2. Atomic Injection
  await db.transaction('rw', [
    db.inventory, db.categories, db.customers, db.sales, 
    db.settings, db.security, db.users, db.expenses, 
    db.debts, db.stock_logs, db.parked_orders
  ], async () => {
    if (data.inventory) await db.inventory.bulkPut(data.inventory);
    if (data.categories) await db.categories.bulkPut(data.categories);
    if (data.customers) await db.customers.bulkPut(data.customers);
    if (data.sales) await db.sales.bulkPut(data.sales);
    if (data.settings) await db.settings.bulkPut(data.settings);
    if (data.security) await db.security.bulkPut(data.security);
    if (data.users) await db.users.bulkPut(data.users);
    if (data.expenses) await db.expenses.bulkPut(data.expenses);
    if (data.debts) await db.debts.bulkPut(data.debts);
    if (data.stock_logs) await db.stock_logs.bulkPut(data.stock_logs);
    if (data.parked_orders) await db.parked_orders.bulkPut(data.parked_orders);
  });

  // 3. Update Activation States
  const licenseExp = data.security?.find((s: any) => s.key === 'license_expiry')?.value;
  const licenseSig = data.security?.find((s: any) => s.key === 'license_signature')?.value;
  const shopName = data.settings?.find((s: any) => s.key === 'shop_name')?.value;

  if (licenseExp) localStorage.setItem('license_expiry', licenseExp);
  if (licenseSig) localStorage.setItem('license_signature', licenseSig);
  if (licenseExp && licenseSig) localStorage.setItem('is_activated', 'true');
  if (shopName) localStorage.setItem('shop_name', shopName);
  
  localStorage.setItem('is_setup_pending', 'false');
  localStorage.setItem('install_skipped', 'true');
  
  return { success: true, shopName: shopName || 'Shop' };
};

export const generateStaffInviteKey = async (user: User) => {
  const sn = await db.settings.get('shop_name');
  const shopName = sn?.value || localStorage.getItem('shop_name') || 'NaijaShop';
  const expiry = localStorage.getItem('license_expiry') || '';
  const license_signature = localStorage.getItem('license_signature') || '';

  const bankSetting = await db.settings.get('softPosBank');
  const numberSetting = await db.settings.get('softPosNumber');
  const accountSetting = await db.settings.get('softPosAccount');

  const data = { 
    shopName, 
    staffName: user.name, 
    staffPin: user.pin, 
    expiry, 
    license_signature,
    softPosBank: bankSetting?.value || '',
    softPosNumber: numberSetting?.value || '',
    softPosAccount: accountSetting?.value || '',
    role: 'staff', 
    secret: 'NAIJA_VERIFIED' 
  };

  const base64String = btoa(JSON.stringify(data));
  const inviteLink = window.location.origin + '/join?key=' + base64String;
  
  const message = `👋 *Hello ${user.name},*\n\nBoss has added you to *${shopName}* on NaijaShop. Click the private link below to set up your terminal automatically:\n\n🔗 ${inviteLink}\n\n_Keep this link secret._`;

  if (navigator.share) {
    try {
      await navigator.share({ title: 'NaijaShop Staff Invite', text: message });
    } catch (e) {
      window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`, '_blank');
    }
  } else {
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`, '_blank');
  }
};

export const processStaffInvite = async (base64Key: string) => {
  try {
    const jsonStr = atob(base64Key);
    const data = JSON.parse(jsonStr);

    if (data.secret !== 'NAIJA_VERIFIED') throw new Error("Invalid invite key");

    await clearAllData();

    localStorage.setItem('user_role', 'staff');
    localStorage.setItem('device_role', 'StaffDevice');
    localStorage.setItem('shop_name', data.shopName);
    localStorage.setItem('is_activated', 'true');
    localStorage.setItem('license_expiry', data.expiry);
    localStorage.setItem('license_signature', data.license_signature);
    localStorage.setItem('is_setup_pending', 'false');

    await db.users.add({
      name: data.staffName,
      pin: data.staffPin,
      role: 'Staff'
    });

    if (data.softPosBank) await db.settings.put({ key: 'softPosBank', value: data.softPosBank });
    if (data.softPosNumber) await db.settings.put({ key: 'softPosNumber', value: data.softPosNumber });
    if (data.softPosAccount) await db.settings.put({ key: 'softPosAccount', value: data.softPosAccount });
    
    await db.security.put({ key: 'license_expiry', value: data.expiry });
    await db.security.put({ key: 'license_signature', value: data.license_signature });

    return { success: true, shopName: data.shopName };
  } catch (e) {
    console.error("Invite processing failed", e);
    return { success: false, error: (e as Error).message };
  }
};

export const reconcileStaffSales = async (staffData: any, adminName: string = 'Admin') => {
  const staffSales = staffData.sales || [];
  const staffDebts = staffData.debts || [];
  const staffCustomers = staffData.customers || [];
  
  let mergedCount = 0;
  let skippedCount = 0;
  let debtsAdded = 0;
  let walletsSynced = 0;

  await db.transaction('rw', [db.inventory, db.sales, db.customers, db.debts, db.stock_logs], async () => {
    for (const sale of staffSales) {
      const existing = await db.sales.where('uuid').equals(sale.uuid).first();
      if (existing) {
        skippedCount++;
        continue;
      }

      for (const item of sale.items) {
        let invItem = await db.inventory.get(item.id);
        if (!invItem) invItem = await db.inventory.where('name').equals(item.name).first();

        if (invItem) {
          const newStock = Math.max(0, (invItem.stock || 0) - item.quantity);
          await db.inventory.update(invItem.id!, { stock: newStock });
          
          await db.stock_logs.add({
            item_id: invItem.id!,
            itemName: invItem.name,
            quantityChanged: -item.quantity,
            previousStock: invItem.stock,
            newStock: newStock,
            type: 'Sales Deduction',
            date: Date.now(),
            staff_name: sale.staff_name || adminName
          });
        }
      }

      const { id, ...saleWithoutOldId } = sale;
      await db.sales.add(saleWithoutOldId);
      mergedCount++;
    }

    for (const debt of staffDebts) {
      let isDuplicate = false;
      if (debt.sale_uuid) {
        const existing = await db.debts.where('sale_uuid').equals(debt.sale_uuid).first();
        if (existing) isDuplicate = true;
      }

      if (!isDuplicate) {
        const { id, ...debtWithoutOldId } = debt;
        await db.debts.add(debtWithoutOldId);
        debtsAdded++;
      }
    }

    for (const sCustomer of staffCustomers) {
      const existing = await db.customers.where('phone').equals(sCustomer.phone).first();
      if (existing) {
        const staffTs = Number(sCustomer.lastTransaction || 0);
        const adminTs = Number(existing.lastTransaction || 0);

        if (staffTs > adminTs) {
          await db.customers.update(existing.id!, {
            walletBalance: sCustomer.walletBalance,
            lastTransaction: staffTs,
            name: sCustomer.name 
          });
          walletsSynced++;
        }
      } else {
        const { id, ...custWithoutOldId } = sCustomer;
        await db.customers.add({
          ...custWithoutOldId,
          lastTransaction: Number(custWithoutOldId.lastTransaction || Date.now())
        });
        walletsSynced++;
      }
    }
  });

  return { 
    success: true, 
    merged: mergedCount, 
    skipped: skippedCount, 
    debtsAdded, 
    walletsSynced 
  };
};

export const exportStaffSalesReport = async (sales: Sale[]) => {
  const sn = await db.settings.get('shop_name');
  const shopName = sn?.value || localStorage.getItem('shop_name') || 'NaijaShop';
  const dateStr = new Date().toISOString().split('T')[0];
  const fileName = `SALES_REPORT_${shopName}_${dateStr}.json.gz`;
  
  const startOfDay = new Date().setHours(0,0,0,0);
  const debts = await db.debts.where('date').aboveOrEqual(startOfDay).toArray();
  const customers = await db.customers.where('lastTransaction').aboveOrEqual(startOfDay).toArray();

  const payload = { 
    sales, 
    debts,
    customers,
    shopName, 
    type: 'STAFF_REPORT', 
    timestamp: Date.now() 
  };

  const jsonString = JSON.stringify(payload);
  const uint8Data = new TextEncoder().encode(jsonString);
  const compressed = pako.gzip(uint8Data);

  if (navigator.share) {
    try {
      const blob = new Blob([compressed], { type: 'application/gzip' });
      const file = new File([blob], fileName, { type: 'application/gzip' });
      await navigator.share({
        title: `Sales Report: ${shopName}`,
        text: `Boss, here is my report for ${dateStr}.`,
        files: [file]
      });
      return { success: true };
    } catch (e) {
      console.error('Share failed', e);
    }
  }

  const blob = new Blob([compressed], { type: 'application/gzip' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
  return { success: true };
};

export const pushInventoryUpdateToStaff = async (resetStock: boolean = false) => {
  const inventory = await db.inventory.toArray();
  const categories = await db.categories.toArray();
  const staffUsers = await db.users.where('role').equals('Staff').toArray();
  
  const sn = await db.settings.get('shop_name');
  const shopName = sn?.value || localStorage.getItem('shop_name') || 'NaijaShop';
  const dateStr = new Date().toISOString().split('T')[0];
  const fileName = `NAIJASHOP_UPDATE_${dateStr}.json`;

  const bankSetting = await db.settings.get('softPosBank');
  const numberSetting = await db.settings.get('softPosNumber');
  const accountSetting = await db.settings.get('softPosAccount');

  const payload = {
    type: 'INVENTORY_UPDATE',
    shopName,
    timestamp: Date.now(),
    inventory,
    categories,
    staffUsers,
    resetStock,
    softPosBank: bankSetting?.value || '',
    softPosNumber: numberSetting?.value || '',
    softPosAccount: accountSetting?.value || ''
  };

  const jsonString = JSON.stringify(payload);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const file = new File([blob], fileName, { type: 'application/json' });

  const message = "Hello Team, I have updated the shop inventory and staff profiles. Please click the file below and select 'Update Shop Inventory' in your app.";

  if (navigator.share) {
    try {
      await navigator.share({
        title: `Shop Update: ${shopName}`,
        text: message,
        files: [file]
      });
      return true;
    } catch (err) {
      console.warn("Navigator share failed, falling back to download");
    }
  }

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
  
  const encodedMessage = encodeURIComponent(message);
  window.open(`https://api.whatsapp.com/send?text=${encodedMessage}`, '_blank');
  return true;
};

export const applyInventoryUpdate = async (data: any) => {
  if (data.type !== 'INVENTORY_UPDATE') {
    throw new Error('Invalid update file type');
  }

  let added = 0;
  let updated = 0;
  const resetStock = data.resetStock === true;
  let shouldLogout = false;
  const currentStaffName = localStorage.getItem('logged_in_staff_name');

  await db.transaction('rw', [db.inventory, db.categories, db.settings, db.users], async () => {
    if (data.softPosBank !== undefined) await db.settings.put({ key: 'softPosBank', value: data.softPosBank });
    if (data.softPosNumber !== undefined) await db.settings.put({ key: 'softPosNumber', value: data.softPosNumber });
    if (data.softPosAccount !== undefined) await db.settings.put({ key: 'softPosAccount', value: data.softPosAccount });

    if (data.categories) {
      for (const cat of data.categories) {
        const { id, ...catWithoutId } = cat;
        const existing = await db.categories.where('name').equals(cat.name).first();
        if (existing) {
          await db.categories.update(existing.id!, catWithoutId);
        } else {
          await db.categories.add(catWithoutId);
        }
      }
    }

    if (data.inventory) {
      for (const item of data.inventory) {
        const { id, stock, ...itemData } = item;
        const existing = await db.inventory.get(id);

        if (existing) {
          const updatePayload = resetStock ? { ...itemData, stock } : itemData;
          await db.inventory.update(id, updatePayload);
          updated++;
        } else {
          const byName = await db.inventory.where('name').equals(item.name).first();
          if (byName) {
            const updatePayload = resetStock ? { ...itemData, stock } : itemData;
            await db.inventory.update(byName.id!, updatePayload);
            updated++;
          } else {
            const { id: bossId, ...newProduct } = item; 
            await db.inventory.add(newProduct);
            added++;
          }
        }
      }
    }

    if (data.staffUsers) {
      let currentLocalStaff = null;
      if (currentStaffName) {
        currentLocalStaff = await db.users.where('name').equals(currentStaffName).first();
      }
      await db.users.where('role').equals('Staff').delete();
      for (const staff of data.staffUsers) {
        const { id, ...staffData } = staff;
        await db.users.add(staffData);
      }
      if (currentStaffName) {
        const updatedStaffRecord = data.staffUsers.find((u: any) => u.name === currentStaffName);
        if (!updatedStaffRecord || (currentLocalStaff && currentLocalStaff.pin !== updatedStaffRecord.pin)) {
          shouldLogout = true;
        }
      }
    }
  });

  if (shouldLogout) {
    alert("Security Update: Boss has updated your profile. Log in again.");
    localStorage.removeItem('user_role');
    localStorage.removeItem('logged_in_staff_name');
    window.location.reload();
  }

  localStorage.setItem('last_inventory_sync', Date.now().toString());
  return { added, updated };
};

export type BackupResult = {
  success: boolean;
  method: 'FILE_SHARE' | 'TEXT_SHARE' | 'DOWNLOAD';
  fileName?: string;
  totalRecords?: number;
  isLarge?: boolean;
};
