
import { Sale, db } from '../db.ts';

export const formatNaira = (amount: number) => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0
  }).format(amount);
};

export const shareReceiptToWhatsApp = (sale: Sale) => {
  const shopName = localStorage.getItem('shop_name') || 'NaijaShop';
  const shopInfo = localStorage.getItem('shop_info') || '';
  const date = new Date(sale.timestamp).toLocaleString('en-NG', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
  
  const transId = sale.id ? String(sale.id).padStart(5, '0') : 'N/A';

  let message = `🛍️ *${shopName.toUpperCase()}*\n`;
  if (shopInfo) message += `📍 ${shopInfo}\n`;
  message += `--------------------------\n`;
  message += `📜 *RECEIPT #${transId}*\n`;
  message += `📅 Date: ${date}\n`;
  message += `--------------------------\n`;
  message += `📦 *ITEMS:*\n`;
  
  sale.items.forEach(item => {
    const itemTotal = item.price * item.quantity;
    message += `• ${item.name} x ${item.quantity} ... ${formatNaira(itemTotal)}\n`;
  });
  
  message += `--------------------------\n`;
  message += `💰 *TOTAL: ${formatNaira(sale.total)}*\n`;
  message += `--------------------------\n`;
  message += `🙏 *Thank you for your business!*\n`;
  message += `\n_Generated by NaijaShop POS_ 🇳🇬`;

  const encodedMessage = encodeURIComponent(message);
  window.open(`https://api.whatsapp.com/send?text=${encodedMessage}`, '_blank');
};

export const generateShopKey = async () => {
  const inventory = await db.inventory.toArray();
  const users = await db.users.toArray();
  const shopName = localStorage.getItem('shop_name') || 'NaijaShop';
  const shopInfo = localStorage.getItem('shop_info') || '';

  const payload = {
    inventory,
    users,
    settings: {
      shopName,
      shopInfo
    }
  };

  const jsonStr = JSON.stringify(payload);
  const base64 = btoa(encodeURIComponent(jsonStr).replace(/%([0-9A-F]{2})/g, (match, p1) => 
    String.fromCharCode(parseInt(p1, 16))
  ));
  
  const key = `SHOP-KEY-${base64}`;
  const message = `🚀 *Shop Setup Key for ${shopName}*\n\nCopy the text below and paste it into your Shop Manager app to sync inventory and staff.\n\n${key}`;

  try {
    await navigator.clipboard.writeText(key);
    alert('Setup Key copied to clipboard! You can now paste it into WhatsApp.');
  } catch (err) {
    console.error('Clipboard failed', err);
  }

  if (navigator.share && key.length < 1500) {
    try {
      await navigator.share({
        title: 'Staff Setup Key',
        text: message
      });
    } catch (e) {
      window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`, '_blank');
    }
  } else {
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(message.substring(0, 1500))}`, '_blank');
  }
};

export const decodeShopKey = (key: string) => {
  const trimmedKey = key.trim();
  if (!trimmedKey.includes('SHOP-KEY-')) return null;
  
  try {
    const match = trimmedKey.match(/SHOP-KEY-([A-Za-z0-9+/=]+)/);
    if (!match) return null;
    
    const base64 = match[1];
    // Fix: correctly decode binary string to percent-encoded string and then to UTF-8
    const jsonStr = decodeURIComponent(Array.prototype.map.call(atob(base64), (c: any) => 
      '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
    ).join(''));
    
    return JSON.parse(jsonStr);
  } catch (e) {
    console.error('Decode error:', e);
    return null;
  }
};

/**
 * Enhanced Backup Function
 * Includes professional naming and share text as requested.
 */
export const backupToWhatsApp = async (data: any) => {
  const { shopName, timestamp } = data;
  const jsonString = JSON.stringify(data, null, 2);
  const dateStr = new Date(timestamp || Date.now()).toISOString().split('T')[0];
  
  // Professional Naming: [ShopName]_Backup_[Date].json
  const safeShopName = (shopName || 'NaijaShop').replace(/\s+/g, '_');
  const fileName = `${safeShopName}_Backup_${dateStr}.json`;
  
  const blob = new Blob([jsonString], { type: 'application/json' });
  const file = new File([blob], fileName, { type: 'application/json' });

  // Professional Share Text
  const shareText = `This is my Secure Shop Backup for ${dateStr}. Keep this file safe. To restore, just share this file back to the POS App.`;

  try {
    // 1. Try Mobile Share API (Direct to WhatsApp with metadata)
    if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        title: `${shopName || 'Shop'} Database Backup`,
        text: shareText,
        files: [file]
      });
      // Update last backup timestamp on success
      await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
      return; 
    }

    // 2. Fail-safe Fallback: Direct File Download
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    // Even if it downloads, we track it as a backup attempt
    await db.settings.put({ key: 'last_backup_timestamp', value: Date.now() });
    alert("Backup saved to downloads. Please send this file to your WhatsApp manually for safekeeping.");
  } catch (err) {
    console.error('Backup failed', err);
    throw err;
  }
};
